name: On push

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Start application
        run: docker compose up -d
      -
        name: Install dependencies
        run: docker exec app-php composer install
      -
        name: Run tests
        run: docker exec app-php vendor/bin/phpunit tst --testdox
